config/routes.rb
Rails.application.routes.draw do
  get 'emails/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  
  get 'projects', to:'pages#projects'
  get 'about', to:'pages#about'
  get 'contact', to:'pages#contact'
  get 'services', to:'pages#services'
  get 'thankyou', to:'pages#thankyou'
  resources :emails
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
     before_save { self.email = email.downcase }
     validates :name, presence: true, length: { maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
     validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
     validates :phone, presence: true, length: { maximum: 10 }
     validates :content, presence: true, length: { maximum: 1000 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def index
  end

  def new
    @email = Email.new
  end
  
  def create
    @email = Email.new(email_params)
    if @email.save
      EmailMailer.new_email(@email).deliver_now
      flash[:info] = "Thank you for the email, we will get back to you shortly"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  

  private

    def email_params
      params.require(:email).permit(:name, :email, :phone,
                                   :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   
   def index
   end
   
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def index
   end
   
   def contact
   end
   
   def about
   end
   
   def services
   end
   
   def thankyou
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/views/home/index.html.erb
<h1 style="text-align:center;"> Freelance Web and Mobile Developer based in Maryland, USA.<br> Highly experienced in developing web and mobile applications.</h1>
<br>

<div class="jumbotron"  id="home-jumbo">
          

  <h1 class="display-3">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>

  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light bg-dark navbar-dark navbar-expand-sm">
  <div class="container">
  <%= link_to "DAG Apps", root_path, class: "navbar-brand", id: "logo" %>
    <ul class="navbar-nav ">
      <li class="nav-item nav-link">
        <%= link_to "Home", root_path, class:"nav-link nav-item" %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to "About", about_path, class:"nav-link nav-item" %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to "Services", services_path, class:"nav-link nav-item" %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to "Projects", projects_path, class:"nav-link nav-item" %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to "Contact", new_email_path, class:"nav-link nav-item" %>
      </li>
    </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/navigation' %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 style="text-align:center;">About Us</h1>
<div class="container " style="border: 4px solid gray;
                               backgroud-color: light-text;">
<div class="card">
  <%= image_tag("about.png", :alt => "rss feed", :class => "card-img-top resize ") %>
  <div class="card-block">
     <h4 class="text-padding">Our Story... </h4>
    <p class="card-text text-padding">We are a team of developers that met at Penn State. We organized clubs, hackathons and competitions. Eventually we started to code together and complete various local projects. Ultimately, we’ve decided it was time to expand our knowledge to a marketplace. Our expertise makes us perfect for large scale developing. We are majoring in computer science, software engineering, graphic design and entrepreneurship! Moreover, we are a team with chemistry and bring enthusiasm to every project! We love the daily challenges from developing and helping clients reach their goals. Hopefully, we can help you too!</p>
  </div>
</div>
</div>

app/views/pages/services.html.erb
<div class="jumbotron jumbotron-fluid" id="services-jumbo">
  <div class="container">
  </div>
</div>

<h3 style="text-align:center;">Our Services</h3>
<div class="row">

<div class="card col-sm-4" style="width: 20rem;">
  <%= image_tag("services/web.jpeg", :alt => "rss feed", :class => "card-img-top card-image-resize") %>
  <div class="card-block ">
    <h4 class="card-title">Web Development</h4>
    <p class="card-text">Our approach to website design is to create a website that strengthens your company’s brand while 
    ensuring ease of use and simplicity for your audience.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

<div class="card col-sm-4" style="width: 20rem;">
  <%= image_tag("services/WP.png", :alt => "rss feed", :class => "card-img-top card-image-resize") %>
  <div class="card-block ">
    <h4 class="card-title">Wordpress</h4>
    <p class="card-text">We have experience in Wordpress, Wix and Weebly and will quickly design sites for you.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

<div class="card col-sm-4" style="width: 20rem;">
  <%= image_tag("services/ios.png", :alt => "rss feed", :class => "card-img-top card-image-resize") %>
  <div class="card-block">
    <h4 class="card-title">Apple Apps</h4>
    <p class="card-text">Our approach is to create an app design that strengthens your company’s brand while ensuring ease of use and simplicity for your audience.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

</div>

<div class="container">
<br>
<h3 style="text-align: center;"> <Strong>Why Us?</Strong></h3>
<br>
<h4> Affordable</h4>
<p>One of the most obvious reasons why businesses are hiring more and more freelance developers is that it is very cost-effective to do so. You can hire freelance web developers within your budget without compromising on quality .</p>
<h4> Trust The Process</h4>
<p>When tasked with a new project our team has developed a system that has proven to be most efficient and time saving. We use wireframing and sketches of every application and ensure that's what our client wants. While developing we regularly update the client and provide feedback and tips to improve the project. We believe strong communication with the client is a key driver to success, so we have made ourselves easy to reach! Lastly, we care about the success of our clients. We understand 
the possible complications that may arise from ambiguity and pledge to be as patient as needed for the success of the project.</p>
</div>
<button type="button" class="btn btn-info">Projects</button>
</div>